# Generated by Django 4.1.7 on 2023-02-19 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Singers',
            new_name='Singer',
        ),
    ]
