# Generated by Django 4.1.7 on 2023-02-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_singers_singer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Singers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Single',
                'verbose_name_plural': 'Singls',
            },
        ),
        migrations.DeleteModel(
            name='Singer',
        ),
    ]
