# Generated by Django 4.1.7 on 2023-02-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_singer_song_delete_singers'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='singers',
            field=models.ManyToManyField(to='main.singer', verbose_name='Singers'),
        ),
    ]
