# Generated by Django 4.1.7 on 2023-02-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_singer_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='feat',
            field=models.ManyToManyField(related_name='Feat', to='main.singer', verbose_name='Feat'),
        ),
    ]
