# Generated by Django 4.1.7 on 2023-02-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_song_feat'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='release_date',
            field=models.DateField(auto_now=True, null=True, verbose_name='Release Date'),
        ),
        migrations.AlterField(
            model_name='song',
            name='feat',
            field=models.ManyToManyField(blank=True, null=True, related_name='Feat', to='main.singer', verbose_name='Feat'),
        ),
        migrations.CreateModel(
            name='Singl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='Singl name')),
                ('release_date', models.DateField(auto_now=True, null=True, verbose_name='Release Date')),
                ('feat', models.ManyToManyField(blank=True, null=True, related_name='Singl_feat', to='main.singer', verbose_name='Feat')),
                ('singers', models.ManyToManyField(to='main.singer', verbose_name='Singls')),
            ],
            options={
                'verbose_name': 'Singl',
                'verbose_name_plural': 'Singls',
            },
        ),
    ]
