# Generated by Django 4.1.7 on 2023-02-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_song_release_date_alter_song_feat_singl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singl',
            name='feat',
            field=models.ManyToManyField(blank=True, null=True, related_name='Singl_feat', to='main.singer', verbose_name='Singl_feat'),
        ),
        migrations.AlterField(
            model_name='singl',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Singl'),
        ),
        migrations.AlterField(
            model_name='singl',
            name='singers',
            field=models.ManyToManyField(to='main.singer', verbose_name='Singl_Singers'),
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
