# Generated by Django 4.1.7 on 2023-02-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_singl_feat_alter_singl_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singl',
            name='release_date',
        ),
        migrations.AddField(
            model_name='singl',
            name='auditions',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='auditions'),
        ),
        migrations.AddField(
            model_name='singl',
            name='registration_date',
            field=models.DateField(auto_now=True, null=True, verbose_name='Release Date'),
        ),
    ]
