# Generated by Django 4.1.7 on 2023-02-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_singl_auditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='singl',
            name='downloads',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Singl_downloads'),
        ),
    ]
