# Generated by Django 4.1.7 on 2023-03-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_singl_downloads'),
    ]

    operations = [
        migrations.CreateModel(
            name='EP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name="Ep's Name")),
                ('auditions', models.IntegerField(blank=True, default=0, null=True, verbose_name="Ep's auditions")),
                ('downloads', models.IntegerField(blank=True, default=0, null=True, verbose_name="Ep's downloads")),
                ('registration_date', models.DateField(auto_now=True, null=True, verbose_name='Release Date')),
                ('Singers', models.ManyToManyField(to='main.singer', verbose_name="Ep's Singers")),
                ('Singls', models.ManyToManyField(to='main.singl', verbose_name="Ep's Singls")),
            ],
            options={
                'verbose_name': 'EP',
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='Album Name')),
                ('auditions', models.IntegerField(blank=True, default=0, null=True, verbose_name='Album_auditions')),
                ('downloads', models.IntegerField(blank=True, default=0, null=True, verbose_name='Album_downloads')),
                ('registration_date', models.DateField(auto_now=True, null=True, verbose_name='Release Date')),
                ('Singers', models.ManyToManyField(to='main.singer', verbose_name='Album_Singers')),
                ('Singls', models.ManyToManyField(to='main.singl', verbose_name='Album_Singls')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
            },
        ),
    ]
